steps:

- name: gcr.io/kaniko-project/executor:latest
  args:
  - --dockerfile=Dockerfile
  - --build-arg=VERSION=${_KANIKO_IMAGE_TAG}
  - --destination=gcr.io/$PROJECT_ID/${_RUNTIME}:${COMMIT_SHA}
  - --destination=gcr.io/$PROJECT_ID/${_RUNTIME}:${_KANIKO_IMAGE_TAG}
  - --cache-repo=gcr.io/$PROJECT_ID/${_RUNTIME}/cache
  - --cache=${_KANIKO_USE_BUILD_CACHE}
  - --no-push=${_KANIKO_NO_PUSH}
  - ${_KANIKO_EXTRA_ARGS}
  waitFor: ['-']

timeout: 600s

substitutions:
  _RUNTIME:
  _KANIKO_IMAGE_TAG: latest
  _KANIKO_NO_PUSH: 'false'
  _KANIKO_USE_BUILD_CACHE: 'true'
  _KANIKO_EXTRA_ARGS:

options:
  substitution_option: ALLOW_LOOSE

tags:
  - knative-lambda-runtime
